# docker compose file to start apache vulnerable server before mitigation

services: 
  vulerable-apache:
    image: vulnerable-apache:latest
    container_name: vulnerable-apache
    ports:
      - "8443:443"
    networks:
      - test_network

networks:
  test_network:
    driver: bridge
