# docker compose file based on `generate-indexer-certs.yml` from wazuh-docker repository

services:
  generator:
    image: wazuh/wazuh-certs-generator:0.0.2
    hostname: wazuh-certs-generator
    volumes:
      - ./config/wazuh_indexer_ssl_certs:/certificates/
      - ./config/certs.yml:/config/certs.yml
