# docker compose file for mitigation on simulated environment 

services: 
  nginx: 
    image: nginx:latest
    container_name: nginx-mitigation 
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
      - ./logs:/var/log/nginx
    networks:
      mitigation_network:
        ipv4_address: 172.25.0.2

  vulnerable-apache:
    image: vulnerable-apache:latest
    container_name: vulnerable-apache
    ports:
      - "8080:80"
    networks:
      mitigation_network:
        ipv4_address: 172.25.0.3

networks:
  mitigation_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16
    
